import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/_styles/globals.css';
import AddTodo from './_components/shared/AddTodo';
import Navigation from './_components/shared/Navigation';
import Search from './_components/shared/Search';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Todo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-200  `}>
        <div className=" w-screen py-20 flex items-center flex-col">
          <AddTodo />
          <Navigation />
          <Search placeholder="Search for a todo..." />
          {children}
        </div>
      </body>
    </html>
  );
}
